In [1]:
import yfinance as yf
ticker = yf.Ticker("AAPL")

In [2]:
ticker.financials          # Income Statement (annual)
ticker.quarterly_financials

ticker.balance_sheet
ticker.quarterly_balance_sheet

ticker.cashflow
ticker.quarterly_cashflow

,2025-09-30,2025-06-30,2025-03-31,2024-12-31,2024-09-30,2024-06-30
Free Cash Flow,2.648600e+10,2.440500e+10,2.088100e+10,2.699500e+10,2.390300e+10,NaN
Repurchase Of Capital Stock,-2.013200e+10,-2.107500e+10,-2.589800e+10,-2.360600e+10,-2.508300e+10,NaN
Repayment Of Debt,-1.185000e+09,-1.770000e+09,9.760000e+08,-8.953000e+09,4.270000e+08,NaN
Issuance Of Debt,0.000000e+00,NaN,NaN,NaN,0.000000e+00,NaN
Capital Expenditure,-3.242000e+09,-3.462000e+09,-3.071000e+09,-2.940000e+09,-2.908000e+09,NaN
Income Tax Paid Supplemental Data,6.037000e+09,5.649000e+09,1.303200e+10,1.865100e+10,6.872000e+09,NaN
End Cash Position,3.593400e+10,3.626900e+10,2.816200e+10,3.029900e+10,2.994300e+10,NaN
Beginning Cash Position,3.626900e+10,2.816200e+10,3.029900e+10,2.994300e+10,2.663500e+10,NaN
Changes In Cash,-3.350000e+08,8.107000e+09,-2.137000e+09,3.560000e+08,3.308000e+09,NaN
Financing Cash Flow,-2.747600e+10,-2.483300e+10,-2.900600e+10,-3.937100e+10,-2.494800e+10,NaN
Cash Flow From Continuing Financing Activities,-2.747600e+10,-2.483300e+10,-2.900600e+10,-3.937100e+10,-2.494800e+10,NaN
Net Other Financing Charges,-2.650000e+08,-2.524000e+09,-3.260000e+08,-2.956000e+09,-4.480000e+08,NaN
Cash Dividends Paid,-3.862000e+09,-3.945000e+09,-3.758000e+09,-3.856000e+09,-3.804000e+09,NaN
Common Stock Dividend Paid,-3.862000e+09,-3.945000e+09,-3.758000e+09,-3.856000e+09,-3.804000e+09,NaN
Net Common Stock Issuance,-2.013200e+10,-2.107500e+10,-2.589800e+10,-2.360600e+10,-2.508300e+10,NaN
Common Stock Payments,-2.013200e+10,-2.107500e+10,-2.589800e+10,-2.360600e+10,-2.508300e+10,NaN
Net Issuance Payments Of Debt,-3.217000e+09,2.711000e+09,9.760000e+08,-8.953000e+09,4.387000e+09,NaN
Net Short Term Debt Issuance,-1.967000e+09,3.903000e+09,3.976000e+09,-7.944000e+09,6.945000e+09,NaN
Short Term Debt Payments,NaN,3.903000e+09,3.976000e+09,-7.944000e+09,NaN,997000000.0
Net Long Term Debt Issuance,-1.250000e+09,-1.192000e+09,-3.000000e+09,-1.009000e+09,-2.558000e+09,NaN
Long Term Debt Payments,-1.250000e+09,-5.673000e+09,-3.000000e+09,-1.009000e+09,-2.558000e+09,NaN
Long Term Debt Issuance,0.000000e+00,NaN,NaN,NaN,0.000000e+00,NaN
Investing Cash Flow,-2.587000e+09,5.073000e+09,2.917000e+09,9.792000e+09,1.445000e+09,NaN
Cash Flow From Continuing Investing Activities,-2.587000e+09,5.073000e+09,2.917000e+09,9.792000e+09,1.445000e+09,NaN
Net Other Investing Changes,-5.050000e+08,-3.400000e+08,-3.200000e+07,-6.030000e+08,-1.910000e+08,NaN
Net Investment Purchase And Sale,1.160000e+09,8.875000e+09,6.020000e+09,1.333500e+10,4.544000e+09,NaN
Sale Of Investment,7.976000e+09,1.402400e+10,1.233800e+10,1.945900e+10,1.512600e+10,NaN
Purchase Of Investment,-6.816000e+09,-5.149000e+09,-6.318000e+09,-6.124000e+09,-1.058200e+10,NaN
Net PPE Purchase And Sale,-3.242000e+09,-3.462000e+09,-3.071000e+09,-2.940000e+09,-2.908000e+09,NaN
Purchase Of PPE,-3.242000e+09,-3.462000e+09,-3.071000e+09,-2.940000e+09,-2.908000e+09,NaN
Operating Cash Flow,2.972800e+10,2.786700e+10,2.395200e+10,2.993500e+10,2.681100e+10,NaN
Cash Flow From Continuing Operating Activities,2.972800e+10,2.786700e+10,2.395200e+10,2.993500e+10,2.681100e+10,NaN
Change In Working Capital,-5.707000e+09,-2.034000e+09,-6.507000e+09,-1.075200e+10,6.608000e+09,NaN
Change In Other Current Liabilities,4.085000e+09,4.180000e+08,-3.581000e+09,-1.199800e+10,1.555000e+10,NaN
Change In Other Current Assets,-3.081000e+09,-1.745000e+09,-5.310000e+09,9.390000e+08,-6.105000e+09,NaN
Change In Payables And Accrued Expense,1.938100e+10,-3.875000e+09,-7.933000e+09,-6.671000e+09,2.119100e+10,NaN
Change In Payable,1.938100e+10,-3.875000e+09,-7.933000e+09,-6.671000e+09,2.119100e+10,NaN
Change In Account Payable,1.938100e+10,-3.875000e+09,-7.933000e+09,-6.671000e+09,2.119100e+10,NaN
Change In Inventory,1.770000e+08,3.650000e+08,6.430000e+08,2.150000e+08,-1.087000e+09,NaN
Change In Receivables,-2.626900e+10,2.803000e+09,9.674000e+09,6.763000e+09,-2.294100e+10,NaN
Changes In Account Receivables,-1.236700e+10,-1.581000e+09,3.669000e+09,3.597000e+09,-1.048500e+10,NaN
Other Non Cash Items,1.659000e+09,4.690000e+08,-2.080000e+08,-2.009000e+09,-3.020000e+08,NaN
Stock Based Compensation,3.183000e+09,3.168000e+09,3.226000e+09,3.286000e+09,2.858000e+09,NaN
Depreciation Amortization Depletion,3.127000e+09,2.830000e+09,2.661000e+09,3.080000e+09,2.911000e+09,NaN
Depreciation And Amortization,3.127000e+09,2.830000e+09,2.661000e+09,3.080000e+09,2.911000e+09,NaN
Net Income From Continuing Operations,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10,1.473600e+10,NaN

In [19]:
ticker.earnings            # annual
ticker.quarterly_earnings

C:\Users\alexv\AppData\Local\Programs\Python\Python313\Lib\site-packages\yfinance\scrapers\fundamentals.py:33: DeprecationWarning: 'Ticker.earnings' is deprecated as not available via API. Look for "Net Income" in Ticker.income_stmt.
  warnings.warn("'Ticker.earnings' is deprecated as not available via API. Look for \"Net Income\" in Ticker.income_stmt.", DeprecationWarning)

In [9]:
ticker.earnings_dates

ImportError: Missing optional dependency 'lxml'.  Use pip or conda to install lxml.

In [10]:
ticker.info["trailingPE"]
ticker.info["forwardPE"]

28.341707

In [13]:
PE = Price / EPS

NameError: name 'Price' is not defined

In [14]:
ticker.dividends
ticker.splits

Date
1987-06-16 00:00:00-04:00    2.0
2000-06-21 00:00:00-04:00    2.0
2005-02-28 00:00:00-05:00    2.0
2014-06-09 00:00:00-04:00    7.0
2020-08-31 00:00:00-04:00    4.0
Name: Stock Splits, dtype: float64

In [15]:
ticker.institutional_holders
ticker.major_holders
ticker.insider_transactions

,Shares,Value,URL,Text,Insider,Position,Transaction,Start Date,Ownership
0,3750,0.0,,Stock Gift at price 0.00 per share.,ADAMS KATHERINE L,General Counsel,,2025-11-12,D
1,3752,1017655.0,,Sale at price 271.23 per share.,KONDO CHRISTOPHER,Officer,,2025-11-07,D
2,4199,1038787.0,,Sale at price 245.89 - 248.73 per share.,PAREKH KEVAN,Chief Financial Officer,,2025-10-16,D
3,16457,NaN,,,PAREKH KEVAN,Chief Financial Officer,,2025-10-15,D
4,7371,NaN,,,KONDO CHRISTOPHER,Officer,,2025-10-15,D
...,...,...,...,...,...,...,...,...,...
71,1852,NaN,,,JUNG ANDREA,Director,,2024-02-01,D
72,1852,NaN,,,BELL JAMES A,Director,,2024-02-01,D
73,1852,NaN,,,LOZANO MONICA C.,Director,,2024-02-01,D
74,1852,NaN,,,GORSKY ALEX,Director,,2024-02-01,D
75,1852,NaN,,,GORE ALBERT A JR,Director,,2024-02-01,D

In [16]:
ticker.options               # дати експірацій
ticker.option_chain(date)

NameError: name 'date' is not defined

In [ ]:
SPY, QQQ, VIX (^VIX), TNX (^TNX)

In [17]:
ticker.news

[{'id': 'd1a7c000-5bf0-34b1-a213-eda51ce77a6e',
  'content': {'id': 'd1a7c000-5bf0-34b1-a213-eda51ce77a6e',
   'contentType': 'STORY',
   'title': 'Apple CEO Tim Cook Could Buy 92,984 iPhone 17s With His 2025 Compensation',
   'description': '',
   'summary': "Apple Inc. (NASDAQ:AAPL) CEO Tim Cook was one of the highest-paid executives in 2024. The CEO saw a slight dip in his 2025 compensation, but still took home an impressive pay package despite Apple stock trailing several leading market indexes for the year. Tim Cook's 2025 Salary and Pay Compensation Cook, who has been CEO of Apple since 2011 when he took over for co-founder Steve Jobs, has helped usher Apple into a new era of growth and taken Apple stock to new milestones. A new filing from Appl",
   'pubDate': '2026-01-12T02:31:08Z',
   'displayTime': '2026-01-12T02:31:08Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/Benzinga/59c001c0e2053cde1c3f1589493ec5e1',
    'originalWidth': 1024,
    'originalHeight': 742,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/_T5RulFey_bly9umcnOW.A--~B/aD03NDI7dz0xMDI0O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Benzinga/59c001c0e2053cde1c3f1589493ec5e1',
      'width': 1024,
      'height': 742,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/y6FgXUtc5igoIzVjEkKBlA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/Benzinga/59c001c0e2053cde1c3f1589493ec5e1',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Benzinga', 'url': 'http://www.benzinga.com/'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/news/apple-ceo-tim-cook-could-023108071.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/apple-ceo-tim-cook-could-023108071.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '488c98a9-2ee9-3852-a32a-5adf3c7fa913',
  'content': {'id': '488c98a9-2ee9-3852-a32a-5adf3c7fa913',
   'contentType': 'STORY',
   'title': 'A 2025 security breach exposed over 184 million private passwords. How to stay safe while you browse',
   'description': '',
   'summary': "'This is a cybercriminal’s dream working list.'",
   'pubDate': '2026-01-11T16:15:00Z',
   'displayTime': '2026-01-11T16:15:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/moneywise_ecomm_711/94d37292ccf6f7da54a8bd52ed826c19',
    'originalWidth': 1000,
    'originalHeight': 549,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/hrKe1OUNp0mFQxDnYaTSQA--~B/aD01NDk7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/moneywise_ecomm_711/94d37292ccf6f7da54a8bd52ed826c19',
      'width': 1000,
      'height': 549,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/bxYvK7JUvOWMfS4pnqtPKQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/moneywise_ecomm_711/94d37292ccf6f7da54a8bd52ed826c19',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Moneywise', 'url': 'https://moneywise.com/'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/news/2025-security-breach-exposed-over-161500826.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/2025-security-breach-exposed-over-161500826.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'a3d63bb3-0e00-3589-a04e-c9ddb9bb2fcf',
  'content': {'id': 'a3d63bb3-0e00-3589-a04e-c9ddb9bb2fcf',
   'contentType': 'STORY',
   'title': 'This Money Expert Is Sending Warning Signs About the Economy — and How To Protect Yourself',
   'description': '',
   'summary': "Several money experts have sounded the alarm, warning that today's economy isn't as strong as some headlines suggest.",
   'pubDate': '2026-01-11T15:07:20Z',
   'displayTime': '2026-01-11T15:07:20Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/gobankingrates_644/8b6c04eefa80977986c3c75810304e76',
    'originalWidth': 1920,
    'originalHeight': 1080,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/P3MW3V6HHeN4Zn2v9PDdpQ--~B/aD0xMDgwO3c9MTkyMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/gobankingrates_644/8b6c04eefa80977986c3c75810304e76',
      'width': 1920,
      'height': 1080,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/36Li5SB6L4TJVeMDlWb7bg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/gobankingrates_644/8b6c04eefa80977986c3c75810304e76',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'GOBankingRates',
    'url': 'https://www.gobankingrates.com/'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/news/money-expert-sending-warning-signs-150720870.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/money-expert-sending-warning-signs-150720870.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '451597cf-08db-318c-80f4-a368ce7b79b9',
  'content': {'id': '451597cf-08db-318c-80f4-a368ce7b79b9',
   'contentType': 'STORY',
   'title': 'Revealed: My 2 Top AI Stock Picks for 2026',
   'description': '',
   'summary': 'With the first full trading week of 2026 now in the books, investors might be wondering if the strong early start in the S&P will precede even more strength. Undoubtedly, a lack of a Santa Claus rally has seemingly paved the way for a rather hot start to 2026, with some memory chip stocks really ... Revealed: My 2 Top AI Stock Picks for 2026',
   'pubDate': '2026-01-11T14:27:54Z',
   'displayTime': '2026-01-11T14:27:54Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/24_7_wall_st__718/e4f2cef6c841fd44ca7eae028c5284cd',
    'originalWidth': 1366,
    'originalHeight': 768,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/Uw63eVjczxOuNWbGrkilQA--~B/aD03Njg7dz0xMzY2O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/24_7_wall_st__718/e4f2cef6c841fd44ca7eae028c5284cd',
      'width': 1366,
      'height': 768,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/fh5yjbI23k.6MailTtp20A--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/24_7_wall_st__718/e4f2cef6c841fd44ca7eae028c5284cd',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': '24/7 Wall St.',
    'url': 'https://247wallst.com/'},
   'canonicalUrl': {'url': 'https://247wallst.com/investing/2026/01/11/revealed-my-2-top-ai-stock-picks-for-2026/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/revealed-2-top-ai-stock-142754736.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '1f73a2e4-6244-3f0f-bb60-044dee319e56',
  'content': {'id': '1f73a2e4-6244-3f0f-bb60-044dee319e56',
   'contentType': 'STORY',
   'title': 'The Surprising Stock About to Join the Nasdaq 100',
   'description': '',
   'summary': 'The Nasdaq 100 is an index most often associated with technology stocks like Nvidia (NASDAQ:NVDA) and Apple (NASDAQ:AAPL) due to its historical focus on innovation and high-growth companies. While it is not a “pure” technology index — there is a separate Nasdaq 100 index devoted exclusively to tech stocks — its heavy tilt towards tech-driven ... The Surprising Stock About to Join the Nasdaq 100',
   'pubDate': '2026-01-11T13:58:58Z',
   'displayTime': '2026-01-11T13:58:58Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/24_7_wall_st__718/3963ba4b68d5bcdffe6655992cb84e97',
    'originalWidth': 1366,
    'originalHeight': 768,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/Kwj4zu1_DyMSEo9AZj2Q7A--~B/aD03Njg7dz0xMzY2O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/24_7_wall_st__718/3963ba4b68d5bcdffe6655992cb84e97',
      'width': 1366,
      'height': 768,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/CvknAgmf2f41dxbnfBpwHw--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/24_7_wall_st__718/3963ba4b68d5bcdffe6655992cb84e97',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': '24/7 Wall St.',
    'url': 'https://247wallst.com/'},
   'canonicalUrl': {'url': 'https://247wallst.com/investing/2026/01/11/the-surprising-stock-about-to-join-the-nasdaq-100/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/surprising-stock-join-nasdaq-100-135858858.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '5b5da359-743f-3c37-bb81-e68948d73293',
  'content': {'id': '5b5da359-743f-3c37-bb81-e68948d73293',
   'contentType': 'STORY',
   'title': 'Exclusive-India proposes forcing smartphone makers to give source code in security overhaul',
   'description': '',
   'summary': 'NEW DELHI, Jan 11 (Reuters) - India proposes requiring smartphone makers to share source code with the government and make several software changes as part of a raft of security measures, prompting behind-the-scenes opposition from giants like Apple and Samsung. The tech companies \u200bhave countered that the package of 83 security standards, which would also include a requirement to alert the government to major software updates, \u200clacks any global precedent and risks revealing proprietary details,',
   'pubDate': '2026-01-11T08:55:34Z',
   'displayTime': '2026-01-11T08:55:34Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/reuters.com/8289558b0515d74db198b78195b51c5d',
    'originalWidth': 800,
    'originalHeight': 533,
    'caption': 'FILE PHOTO: The Indian flag, Apple, Google, Samsung logos and a surveillance camera are seen in this illustration taken December 4, 2025. REUTERS/Dado Ruvic/Illustration/File Photo',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/BRrU65uzX0L10cmBQ25m8A--~B/aD01MzM7dz04MDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/reuters.com/8289558b0515d74db198b78195b51c5d',
      'width': 800,
      'height': 533,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/0k0C4gxVlstRbt3Fz.JKQw--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/reuters.com/8289558b0515d74db198b78195b51c5d',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Reuters', 'url': 'https://www.reuters.com/'},
   'canonicalUrl': {'url': 'https://www.yahoo.com/news/articles/exclusive-india-proposes-forcing-smartphone-083749578.html',
    'site': 'news',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://www.yahoo.com/news/articles/exclusive-india-proposes-forcing-smartphone-083749578.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '28bef89b-4167-3907-8b50-80e98846caf7',
  'content': {'id': '28bef89b-4167-3907-8b50-80e98846caf7',
   'contentType': 'STORY',
   'title': 'Prediction: These 2 Unstoppable Stocks Will Join Nvidia, Alphabet, Apple, and Microsoft in the $3 Trillion Club by 2027',
   'description': '',
   'summary': 'These two industry powerhouses have a clear path to admission to the elite $3 trillion club.',
   'pubDate': '2026-01-11T08:22:00Z',
   'displayTime': '2026-01-11T08:22:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/870921f1042b4bc40f909303bf7a94f3',
    'originalWidth': 1400,
    'originalHeight': 934,
    'caption': 'A smiling person holding a notebook looking at the upward trajectory of graph lines.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/6bEn70TfcgQWS7b.cpforw--~B/aD05MzQ7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/870921f1042b4bc40f909303bf7a94f3',
      'width': 1400,
      'height': 934,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/uiYp5BDa8axqUFCsFJUnlw--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/870921f1042b4bc40f909303bf7a94f3',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool', 'url': 'http://www.fool.com/'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/01/11/prediction-2-unstoppable-stocks-3-trillion/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/prediction-2-unstoppable-stocks-join-082200634.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '1074d4c2-5b74-4870-ab17-6c05b2fde668',
  'content': {'id': '1074d4c2-5b74-4870-ab17-6c05b2fde668',
   'contentType': 'STORY',
   'title': "'There were huge markups in diamond rings before we came along'",
   'description': '',
   'summary': 'Tobias Kormind’s entry into one of the most secretive industries began over 20 years ago when his sister married into a third-generation diamond-cutting family.',
   'pubDate': '2026-01-11T06:00:14Z',
   'displayTime': '2026-01-11T06:00:14Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2022-10/785ca6e0-4ef7-11ed-bdbb-655760021ba3',
    'originalWidth': 5700,
    'originalHeight': 3800,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/5fXH0ukgCGGL02yFfCezBg--~B/aD0zODAwO3c9NTcwMDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-uploaded-images/2022-10/785ca6e0-4ef7-11ed-bdbb-655760021ba3',
      'width': 5700,
      'height': 3800,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/Hj5cR39sr44QQoZhjYTomQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://s.yimg.com/os/creatr-uploaded-images/2022-10/785ca6e0-4ef7-11ed-bdbb-655760021ba3',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance UK',
    'url': 'http://uk.finance.yahoo.com/'},
   'canonicalUrl': {'url': 'https://uk.finance.yahoo.com/news/diamonds-online-price-rings-uk-business-060014031.html',
    'site': 'finance',
    'region': 'GB',
    'lang': 'en-GB'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/diamonds-online-price-rings-uk-business-060014031.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'b9b55b8a-f848-3d18-aa56-28d884c7d0d3',
  'content': {'id': 'b9b55b8a-f848-3d18-aa56-28d884c7d0d3',
   'contentType': 'STORY',
   'title': 'Dan Ives: Trillions in AI Spending Are Just the Start of ‘Fourth Industrial Revolution’',
   'description': '',
   'summary': 'Dan Ives has traveled more than 3 million miles over 25 years, touring data centers, and meeting CEOs and CIOs where AI is being built.',
   'pubDate': '2026-01-11T05:01:00Z',
   'displayTime': '2026-01-11T05:01:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/the_daily_upside_435/d0956b65270a68ae7018ba894d012c87',
    'originalWidth': 1600,
    'originalHeight': 900,
    'caption': 'Photo illustration of an iceberg floating in water, with the larger part underwater covered in binary code',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/zliAb7RW.eWZmgT7d6OcEA--~B/aD05MDA7dz0xNjAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/the_daily_upside_435/d0956b65270a68ae7018ba894d012c87',
      'width': 1600,
      'height': 900,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/VkWCM1RjbdZSdAFzIUryXA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/the_daily_upside_435/d0956b65270a68ae7018ba894d012c87',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'The Daily Upside',
    'url': 'http://thedailyupside.com/'},
   'canonicalUrl': {'url': 'https://www.thedailyupside.com/technology/artificial-intelligence/dan-ives-trillions-in-ai-spending-are-just-the-start-of-fourth-industrial-revolution/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/dan-ives-trillions-ai-spending-050100323.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '1e0b6360-1ee5-32d3-920a-ae28c6c28854',
  'content': {'id': '1e0b6360-1ee5-32d3-920a-ae28c6c28854',
   'contentType': 'STORY',
   'title': 'Palantir Billionaire Peter Thiel Dumped Nvidia and Bought This Other Magnificent Stock Instead -- Even as Warren Buffett Was Selling It Before Retiring',
   'description': '',
   'summary': "Peter Thiel's hedge fund recently exited his entire stake in Nvidia stock.",
   'pubDate': '2026-01-10T16:50:00Z',
   'displayTime': '2026-01-10T16:50:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/d804c974113acb9992fb4fa2393f88a2',
    'originalWidth': 1400,
    'originalHeight': 840,
    'caption': 'Nvidia headquarters with logo on sign out front.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/bE1XcGqByB8jAxdH.09D1Q--~B/aD04NDA7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/d804c974113acb9992fb4fa2393f88a2',
      'width': 1400,
      'height': 840,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/BGukCuqNP90TC3f5m1XDOA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/d804c974113acb9992fb4fa2393f88a2',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool', 'url': 'http://www.fool.com/'},